### ISSUE TITLE
AirPlay lagging after trying to root my TV

### ISSUE THREAD

**Issue by ChrisJanson** [RootMyTV/RootMyTV.github.io#101]
Hello Developers, 

after I tried to root my TV my AirPlay lags every second in image and audio. The root process was not successful.
Completely resetting the TV was not helping, is it possible to remove the data manually ?

**Comment by Informatic** [comment]
Factory resetting the TV gets rid of all the files that have been touched
by RootMyTV (also - that probably wasn't even needed, since we just create
one file in an unused temporary directory, and one file in a configuration
directory, which is not read by "patched" firmware versions) - I think this
may be very much unrelated.

**Comment by ChrisJanson** [comment]
Okay, before I tried to root the device, it was working fine. Was there any problem with airplay in the past with the rooting process ?
