### ISSUE TITLE
[REQ] Mock WebOS version

### ISSUE THREAD

**Issue by psychowood** [RootMyTV/RootMyTV.github.io#12]
Hi,
I was wondering it if could be possible to make the TV believe it is running a different WebOS version. It could be useful to try newer packages from the LG Content Store, for example, since I'm quite sure that a lot of packages aren't really incompatible between different versions (e.g. my 2019 C9 is running webos 4.9 and LG decided not to make Stadia and Geforce Now available below webos 5.0).

TIA

**Comment by Informatic** [comment]
More likely issue is that these applications would depend on some newer APIs. Changing regions, if an app is limited to some specific ones, should be doable, but that is out of the scope of this project. (and definitely not something we would be able to add without much effort)

Regardless, drop by [OpenLGTV Discord](https://github.com/RootMyTV/RootMyTV.github.io#troubleshooting) if you are interested in reverse engineering these things, since seems like we have some people interested in that as well.

**Comment by Informatic** [comment]
When I think about it, it now actually makes sense in regards to a different thing - see: https://github.com/webosbrew/webos-homebrew-channel/issues/75
