### ISSUE TITLE
Option to not install homebrew ipk

### ISSUE THREAD

**Issue by mcchas** [RootMyTV/RootMyTV.github.io#13]
I tried running this locally with a modified stage3.sh that does not attempt to install the IPK - it attempts the exploit via third-party-login but hits a network error. I assume its because of my self-signed certificate. Is there any chance you can host a version that does not install this? I only want the shell..

**Comment by Informatic** [comment]
OK, hold on. That's a different thing.

So if you are hitting network error in third-party-login, then the issue is that third-party-login *needs* to have HTTPS exposed (with proper certificates) on the domain that hosts stage2. (we only provide part of a domain to third-party-login app *without* https:// prefix, and that one is appended in the app itself)

You can always just install everything normally, set up your own `start-devmode.sh`, and finally remove Homebrew Channel afterwards.
