### ISSUE TITLE
NAND Dumper ? (LG OLED C9)

### ISSUE THREAD

**Issue by mcohrs** [RootMyTV/RootMyTV.github.io#34]
Any chance I can do a full nand dump?

Im a bit worried to brick the TV when messing around to much with the OS via SSH.

Are there any other recovery options such as: 

- boot loader
- recovery partiotion
- etc ? 

Thanks for your help.

Amazing work btw <3

**Comment by Informatic** [comment]
There is a way of getting into the bootloader, however this requires access to a working system to enable first. (also this is not public/documented anywhere, and requires some additional hardware - docs regarding this may get published at some point)

If you only stick to customizations via scripts executed on boot in `/var/lib/webosbrew/init.d` (note: you most probably won't be able to change anything else persistently anyways, since most partitions are read-only and **are cryptographically signed**), we have safeguards in place to disable these in case something bad happens. ("Failsafe Mode" - if a TV crashes on boot you only get recovery telnet server you can access to roll back any breaking changes you've potentially made)

**Comment by levihb** [comment]
@Informatic I'm new to all of this. Why can't we disable the partition signing if we have root?

**Comment by mcohrs** [comment]
Thanks for clarifying this :)
